# Generated by Django 3.0.7 on 2020-06-26 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='price',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='url',
        ),
    ]
