
# Generated by Django 3.0.7 on 2020-06-26 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200626_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Receipe',
        ),
    ]
